# Generated by Django 4.1.3 on 2022-11-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadfilemodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadfilemodel',
            table='uploads',
        ),
    ]
