# Generated by Django 4.1.4 on 2022-12-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_materials_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='materials',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app.materials'),
        ),
    ]
