# Generated by Django 4.1.2 on 2022-12-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_project_ideafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='project',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AddField(
            model_name='materials',
            name='project',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='project',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AddField(
            model_name='quizrepo',
            name='project',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='project',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AlterField(
            model_name='relations',
            name='project',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
