# Generated by Django 4.1.3 on 2022-11-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='filename',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='uploadfilemodel',
            table='filesUploaded',
        ),
    ]
