# Generated by Django 4.1.3 on 2022-11-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadfilemodel_filename_alter_uploadfilemodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='filename',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
