# Generated by Django 3.2.6 on 2022-12-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_quiz_quiz_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='user_id',
            new_name='user',
        ),
    ]
