# Generated by Django 3.2.6 on 2022-12-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_user_id_quiz_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='q_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quizrepo',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quizrepo',
            old_name='user_id',
            new_name='user',
        ),
    ]
