# Generated by Django 3.2.6 on 2022-12-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20221206_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
