# Generated by Django 4.1.3 on 2022-12-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_answer_isanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='filename',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='uploadfilemodel',
            table='uploadfile',
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
