# Generated by Django 4.1.2 on 2022-12-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_project_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='userId',
            new_name='user',
        ),
    ]
