# Generated by Django 4.1.3 on 2022-12-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_filename_uploadfilemodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('ideafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uploadfilemodel')),
            ],
            options={
                'db_table': 'groupfiles',
            },
        ),
    ]
