# Generated by Django 4.1.3 on 2022-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_groupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='ideafile',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
