# Generated by Django 4.1.3 on 2022-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_groupmodel_ideafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
