# Generated by Django 4.1.3 on 2022-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_uploadfilemodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='ideafile',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
