# Generated by Django 4.1.3 on 2022-12-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_userid_project_user'),
        ('app', '0016_alter_groupmodel_ideafile'),
    ]

    operations = [
    ]
