# Generated by Django 3.2.6 on 2022-12-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_userid_project_user'),
        ('app', '0016_alter_groupmodel_ideafile'),
    ]

    operations = [
    ]
